- src/components/interfaces/MOBILE_API.xml
Add minlength parameter in MobileAPI
> APPLINK-12295 Add minlength parameter in MobileAPI

- src/components/transport_manager/include/transport_manager/transport_manager_impl.h
- src/components/transport_manager/src/transport_manager_impl.cc
Add synchronization for the next TransportManager fields:
* TMIpl::connections_
* TMIpl::Handle2GUIDConverter::conversion_table_
* TMIpl::device_to_adapter_map_
* TMIpl::device_list_
> TM fields synchronisation

- src/components/application_manager/src/application_impl.cc
- src/components/application_manager/src/application_manager_impl.cc
- src/components/policy/src/policy/src/cache_manager.cc
- src/components/policy/src/policy/src/sql_pt_queries.cc
- src/components/policy/src/policy/src/sql_pt_representation.cc
- src/components/security_manager/src/ssl_context_impl.cc
- src/components/transport_manager/src/transport_adapter/transport_adapter_impl.cc
- src/components/transport_manager/src/transport_adapter/transport_adapter_listener_impl.cc
- src/components/transport_manager/src/usb/libusb/usb_connection.cc
- src/components/transport_manager/src/usb/libusb/usb_handler.cc
- src/components/transport_manager/src/usb/usb_aoa_adapter.cc
- src/components/transport_manager/src/usb/usb_connection_factory.cc
- src/components/transport_manager/src/usb/usb_device_scanner.cc
The PR contains fixes for blocker items on GENIVI
> Stabilization

- src/components/application_manager/include/application_manager/commands/hmi/dial_number_request.h
- src/components/application_manager/include/application_manager/commands/hmi/dial_number_response.h
- src/components/application_manager/include/application_manager/commands/mobile/dial_number_request.h
- src/components/application_manager/include/application_manager/mobile_command_factory.h
- src/components/application_manager/include/application_manager/request_controller.h
- src/components/application_manager/include/application_manager/request_info.h
- src/components/application_manager/src/commands/hmi/dial_number_request.cc
- src/components/application_manager/src/commands/hmi/dial_number_response.cc
- src/components/application_manager/src/commands/mobile/dial_number_request.cc
- src/components/application_manager/src/hmi_command_factory.cc
- src/components/application_manager/src/mobile_command_factory.cc
- src/components/application_manager/src/request_controller.cc
- src/components/application_manager/src/request_info.cc
- src/components/include/utils/date_time.h
- src/components/include/utils/timer_thread.h
- src/components/utils/src/date_time.cc
Problem: SDL freezes after receiving DialNumber request
Detail please see in APPLINK-17083
> Fix of SDL. Correction processing DialNumber request.

- src/components/application_manager/src/state_controller_impl.cc
Partially implements #[0273](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0273-webengine-projection-mode.md)
- ATF scripts (will be added while ready)
- Unit tests will be provided as separate PR 
The PR adds HMI Level setup for WebEngine Projections apps, as well as VideoStreaming state and AudioStreaming state for different HMI levels.
> Implement HMI states management for WEP apps

- .gitmodules
- src/components/application_manager/include/application_manager/commands/command_notification_impl.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/on_app_interface_unregistered_notification.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/on_exit_application_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_app_interface_unregistered_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/hmi_notifications_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_app_interface_unregistered_notification_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/simple_notification_commands_test.cc
- src/components/application_manager/src/commands/command_notification_impl.cc
- src/components/interfaces/HMI_API.xml
- src/components/protocol_handler/src/protocol_handler_impl.cc
- src/components/transport_manager/include/transport_manager/websocket_server/websocket_connection.h
- src/components/transport_manager/include/transport_manager/websocket_server/websocket_secure_session.h
- src/components/transport_manager/include/transport_manager/websocket_server/websocket_session.h
- src/components/transport_manager/src/transport_manager_impl.cc
- src/components/transport_manager/src/websocket_server/websocket_connection.cc
- src/components/transport_manager/src/websocket_server/websocket_secure_session.cc
- src/components/transport_manager/src/websocket_server/websocket_session.cc
- src/components/transport_manager/test/transport_manager_impl_test.cc
Fixes #[0273](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0273-webengine-projection-mode.md)
This PR is **not ready** for review.
This PR makes **minor** API changes.
Rpc_spec https://github.com/LuxoftSDL/rpc_spec/pull/1
Use scripts from https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/2
The PR adds RESOURCE_CONSTRAINT to HMI API and its processing to onExitApplicationNotification, updates unit tests.
> Add new application exit reason RESOURCE_CONSTRAINT

- src/appMain/sdl_preloaded_pt.json
- src/components/application_manager/include/application_manager/smart_object_keys.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/bc_on_app_capability_updated_notification.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/on_app_capability_updated_notification.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/bc_on_app_capability_updated_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_app_capability_updated_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/hmi_command_factory.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/mobile_command_factory.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/bc_on_app_capability_updated_notification_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_app_capability_updated_notification_test.cc
- src/components/application_manager/src/smart_object_keys.cc
- src/components/interfaces/HMI_API.xml
Fixes [FORDTCN-6890](https://adc.luxoft.com/jira/browse/FORDTCN-6890)
This PR makes **mino** API changes.
Add Unit Test for the new RPC OnAppCapabilityUpdated.
This PR provides the changes that add the new one RPC OnAppCapabilityUpdated.
> Add SDL ability to forward the new OnAppCapabilityUpdated RPC from application to the HMI

- src/components/application_manager/src/resumption/resumption_data_processor.cc
Fixes #7001(https://adc.luxoft.com/jira/browse/FORDTCN-7001)
Changed consecutive command number calculation during app resumption
> Fix AddCommand resumption order

- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/sdl_pending_resumption_handler.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_pending_resumption_handler.cc
Crash was happening due to invalid accessing to map
> Fix crash on plugin destruction

- src/components/application_manager/include/application_manager/resumption/resumption_data_processor.h
- src/components/application_manager/src/resumption/resumption_data_processor.cc
Fixes #[6991](https://adc.luxoft.com/jira/browse/FORDTCN-6991)
This PR is **not ready** for review.
Fix problem with incorrect deleting of commands during resumption
> Fix problem with incorrect deleting of commands during resumption

- src/components/application_manager/src/resumption/resumption_data_processor.cc
Fixes #[7094](https://adc.luxoft.com/jira/browse/FORDTCN-7094)
Needs to be merged after PR#[69](https://github.com/LuxoftSDL/sdl_core/pull/69)
This PR is **not ready** for review.
Fix redundant delete submenu requests
> Fix redundant delete submenu requests

- src/appMain/hmi_capabilities.json
Synchronized default systemCapabilities on core and HMI
> Sync sdl core default capabilities with HMI caps

- src/components/application_manager/test/state_controller/state_controller_test.cc
In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-6865
- Fix state_controller_unit_tests
In accordance with the [[SDL-0190] Handle response from HMI during resumption data](https://github.com/LuxoftSDL/sdl_core/pull/84) implementation
> [SDL-0190] Update state controller unit tests

- src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/vehicle_info_pending_resumption_test.cc
Add smart expectation for message helper functions
> Add expects for message helper function in ResumptionHandler Unit tests

- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/hmi_notifications_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/add_command_request_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/create_interaction_choice_set_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/register_app_interface_request_test.cc
- src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/vehicle_info_pending_resumption_test.cc
- src/components/application_manager/test/app_launch/app_launch_ctrl_test.cc
- src/components/application_manager/test/application_impl_test.cc
- src/components/application_manager/test/include/application_manager/mock_resume_ctrl.h
> [SDL-0190] Impl/fix build with cotire off

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_app_extension.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_helpers.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_pending_resumption_handler.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/interior_data_manager_impl.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_rpc_plugin.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/button_press_request_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/get_interior_vehicle_data_request_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/on_interior_vehicle_data_notification_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/rc_get_interior_vehicle_data_consent_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/set_interior_vehicle_data_request_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/include/rc_rpc_plugin/mock/mock_rc_helpers.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/mock_rc_helpers.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_app_extension_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/resource_allocation_manager/CMakeLists.txt
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/resource_allocation_manager/resource_allocation_manager_impl_test.cc
Fixes #[FORDTCN-7212](https://adc.luxoft.com/jira/browse/FORDTCN-7212)
CLA
- [x ] I have signed [the CLA](https://docs.google.com/forms/d/e/1FAIpQLSdsgJY33VByaX482zHzi-xUm49JNnmuJOyAM6uegPQ2LXYVfA/viewform)
> [SDL-0188] Impl/sdl restore interior vehicle data subscriptions

- src/components/application_manager/src/resumption/resumption_data_processor.cc
This PR provides module data checking in a response from a HMI.
> Add module data checking in a response from HMI

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_pending_resumption_handler.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_rpc_plugin.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_rpc_plugin.cc
- src/components/application_manager/src/application_impl.cc
- src/components/application_manager/src/resumption/resumption_data_processor.cc
In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-7378
Draft fixes for several issues in ./test_scripts/Resumption/Handling_errors_from_HMI/005_resume_all_data_with_one_error_rpc_unexpected_disconnect.lua 
Need to refactor for better reading.
> [SDL-0188 ]Several fixes for RC restoring

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/include/rc_rpc_plugin/mock/mock_interior_data_manager.h
> [SDL-0188] fixup! Fix proper IVD cache cleaning on data revert

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/get_interior_vehicle_data_request.cc
Remove redundant code. It shouldn't be in the feature branch, it's not actual https://github.com/LuxoftSDL/sdl_core/pull/115 
The valid fix was provided in https://github.com/LuxoftSDL/sdl_core/pull/117
> [SDL-0188] fixup! Fix first app subscription

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_pending_resumption_handler.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc
Fixes #[JIRA-7383](https://adc.luxoft.com/jira/browse/FORDTCN-7383)
Fixed behavior for freeze and repeat request after successful response.
> [SDL-0188] Fix resume 2nd app in case of different module types

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/CMakeLists.txt
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_penfing_resumption_handler_test.cc
Fixes #[JIRA-7366](https://adc.luxoft.com/jira/browse/FORDTCN-7366)
Added Uts for the restore interior vehicle data subscriptions during resumption.
> [SDL-0188] UTs

- src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_app_extension.h
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/get_interior_vehicle_data_request.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_app_extension_test.cc
- src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_pending_resumption_handler_test.cc
Fixes #[FORDTCN-7369](https://adc.luxoft.com/jira/browse/FORDTCN-7369)
Avoid multiple calls UpdateHash during resumption
> Update behavior for UpdateHash

- src/components/interfaces/HMI_API.xml
Implements https://adc.luxoft.com/jira/browse/FORDTCN-11077 
rpc_spec from https://github.com/LuxoftSDL/rpc_spec/pull/13
> [SDL-0293] Add systemHardwareVersion parameter 

- src/components/application_manager/include/application_manager/application.h
- src/components/application_manager/include/application_manager/application_impl.h
- src/components/application_manager/include/application_manager/message_helper.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/subscribe_button_request.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/subscribe_button_response.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/subscribe_button_request.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_request.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_response.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/subscribe_button_request.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/hmi_command_factory.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/register_app_interface_request_test.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/subscribe_button_request_test.cc
- src/components/application_manager/src/application_impl.cc
- src/components/application_manager/src/hmi_interfaces_impl.cc
- src/components/application_manager/src/message_helper/message_helper.cc
- src/components/application_manager/test/include/application_manager/mock_application.h
- src/components/application_manager/test/include/application_manager/mock_message_helper.h
- src/components/application_manager/test/mock_message_helper.cc
- src/components/interfaces/HMI_API.xml
Fixes [FORDTCN-12166](https://adc.luxoft.com/jira/browse/FORDTCN-12166)
This PR makes **major** API changes.
ATF test scripts, affected UTs are updated
Add HMI subscribe button request and response
> [SDL 0192] Add subscribe button request

- src/components/application_manager/include/application_manager/commands/button_notification_to_mobile.h
- src/components/application_manager/include/application_manager/message_helper.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/on_button_event_notification.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/on_button_press_notification.h
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_event_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_button_press_notification.cc
- src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_button_notification_commands_test.cc
- src/components/application_manager/src/commands/button_notification_to_mobile.cc
- src/components/application_manager/src/message_helper/message_helper.cc
- src/components/application_manager/test/include/application_manager/mock_message_helper.h
- src/components/application_manager/test/mock_message_helper.cc
Fixes [FORDTCN-12261](https://adc.luxoft.com/jira/browse/FORDTCN-12261)
Shared base class for mobile button notifications is added to unify behavior of OnButton notifications and fix several issues.
> [SDL 0192] add shared class for button notifications to mobile

- src/components/application_manager/include/application_manager/app_launch/app_launch_ctrl_impl.h
- src/components/application_manager/src/app_launch/app_launch_ctrl_impl.cc
[Things to note: Pull Requests **must** fix an issue. Discussion about the feature / bug takes place in the issue, discussion of the implementation takes place in the PR. Please also see the [Contributing Guide](https://github.com/smartdevicelink/sdl_core/blob/master/.github/CONTRIBUTING.md) for information on branch naming and the CLA, and the [SmartDeviceLink GitHub Best Practices](https://d83tozu1c8tt6.cloudfront.net/media/resources/SDL_GitHub_BestPractices.pdf) document for more information on how to enter a pull request. Once this PR is ready for review, please request one from @JackLivio.
Delete the above section when you've read it.]
Fixes #[issue number]
This PR is **[ready / not ready]** for review.
This PR makes **[no / minor / major]** API changes.
[Describe how you plan to …
> Review comments fix
