src/components/application_manager/src/application_impl.cc
src/components/application_manager/src/application_manager_impl.cc

Defect: Sends OnVideoDataStreaming/OnAudioDataStreaming true/false after every packet
Closses-Bug: APPLINK-17089

Fix of SDL incorrect timeout for Audio/VideoStreaming

---

src/components/application_manager/include/application_manager/message_helper.h
src/components/application_manager/src/commands/mobile/register_app_interface_request.cc
src/components/application_manager/src/commands/mobile/register_app_interface_response.cc
src/components/application_manager/src/message_helper.cc
src/components/application_manager/src/policies/policy_handler.cc
src/components/policy/src/policy/src/policy_manager_impl.cc

1. OnSystemRequestNotyfication send to mobile
SDL doesn't initiate PTU when new app has registered. APPLINK-17143
2. Fix for OnSystemRequest will sent if mobile use protokol v.4
SDL doesn't send OnSystemRequest(QUERY_APPS) to the App. APPLINK-17438

Fix of GENIVI: Sdl doesnt send OnSystemRequests

---

src/components/application_manager/src/hmi_capabilities_impl.cc
src/components/application_manager/test/hmi_capabilities_test.cc

Fixes [Jira link](https://adc.luxoft.com/jira/browse/FORDTCN-5842)
**Reproduction Steps**
1. Value of HMICapabilitiesCacheFile parameter is defined (hmi_capabilities_cache.json) in smartDeviceLink.ini file
2. HMI capability cash file (hmi_capabilities_cache.json) exists on file system
3. All HMI Capabilities (VR/TTS/RC/UI etc) are presented in hmi_capabilities_cache.json
4. SDL and HMI are started
5. Mobile sends RegisterAppInterface request to SDL
**Testing Plan**
Testing with ATF and UT
**Summary**
Added enum for correct convert and saving prerecordedSpeechCapabilities
**!! Can be merge only after [PR with refactor hmi_capabilities_test](https://github.com/LuxoftSDL/sdl_core/pull/17)**
**CLA**

Fix wrong convert PrerecordedSpeech

---

src/components/application_manager/src/hmi_capabilities_impl.cc

Fix for [5895](https://adc.luxoft.com/jira/browse/FORDTCN-5895)
pcm_stream_capabilities parameter was missed in the HMI API, after adding it (it was done in the scope of [4188](https://adc.luxoft.com/jira/browse/FORDTCN-4188) ) - we also need to add the saving of this parameter to the cache file

Save pcm_stream_capabilities to the cache

---

src/components/application_manager/src/hmi_capabilities_impl.cc
src/components/application_manager/test/hmi_capabilities_test.cc

Fix for [5843](https://adc.luxoft.com/jira/browse/FORDTCN-5843)
Persists audioPassThruCapabilitiesList to  HMI Capabilities cache file like array.

Saved audioPassThruCapabilities like array to hmi_capabilities_cache_file

---

src/components/policy/policy_regular/include/policy/policy_table/types.h
src/components/policy/policy_regular/include/policy/pt_representation.h
src/components/policy/policy_regular/include/policy/sql_pt_representation.h
src/components/policy/policy_regular/src/cache_manager.cc
src/components/policy/policy_regular/src/policy_table/types.cc
src/components/policy/policy_regular/src/sql_pt_queries.cc
src/components/policy/policy_regular/src/sql_pt_representation.cc

Fix for [5843](https://adc.luxoft.com/jira/browse/FORDTCN-5841)
Removed functional where SDL sets the wersCountryCode parameter in 'ignition_cycles_since_last_exchange' section of LocalPT (policy_regular build)
This code was added by me in this [commit](https://github.com/LuxoftSDL/sdl_core/commit/309671f16072568421cf22f57d7747b78331f938) but because it is not used and leads to failed some script - I removed it.

Removed functional where SDL sets the wersCountryCode to LocalPT

---

src/components/application_manager/test/hmi_capabilities_test.cc
src/components/policy/policy_regular/src/cache_manager.cc
src/components/policy/policy_regular/src/policy_table/types.cc

Fixes [jira link](https://adc.luxoft.com/jira/browse/FORDTCN-6126)
Don't save ccpu_version in PTS. 
Be informed that this code was added by me in this [commit](https://github.com/LuxoftSDL/sdl_core/commit/309671f16072568421cf22f57d7747b78331f938)

PTS contains ccpu version

---

src/components/application_manager/src/hmi_capabilities_impl.cc
src/components/application_manager/test/hmi_capabilities_test.cc

[Jira Task](https://adc.luxoft.com/jira/browse/FORDTCN-6161)
Received GetSystemInfoResponse with ccpu_version 
1. If local ccpu_version matches with received ccpu_version from HMI, and cache exist SDL Core should respond all pending RAI requests, this is possible if set the hmi_cooperating to true.
2. If local ccpu_version matches with received ccpu_version from HMI, and cache does't exist, SDL Core should not respond all holded RAI requests, before will be processed required requests for capabilitiesit's. It's mean that hmi_cooperating need to be false until required requests will be  proccesed.

Suspend response to RAI requests until HMI has responded to all the HMI capabilities

---

src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/hmi/vi_get_vehicle_type_request_test.cc
src/components/application_manager/test/application_manager_impl_test.cc
src/components/application_manager/test/hmi_capabilities_test.cc

This PR increase unit tests coverage on persistence HMI capabilities . The commit created as fixup for [commit](https://github.com/LuxoftSDL/sdl_core/commit/b0995be0042cc6ab78f57795906c320ac86da129)

Increase UT coverage for persisting hmi capabilities

---

src/components/application_manager/include/application_manager/application_manager_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/create_window_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/create_window_request_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/register_app_interface_request_test.cc
src/components/application_manager/src/application_manager_impl.cc
src/components/include/application_manager/application_manager.h
src/components/include/test/application_manager/mock_application_manager.h

Fixes: [0273](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0273-webengine-projection-mode.md)
[JIRA](https://adc.luxoft.com/jira/browse/FORDTCN-5926)
Unit tests are included in current PR
ATF test scripts will be created afrewards as separate PR.
- Implemented internal SDL setup of default template screen layout for apps registered with AppHMIType "WEB_VIEW"
- Implemented Widgets rejection while app has active template WEB_VIEW 
- Added unit test cases for RAI requests and for CreateWindow requests which cover the functionality described above.

SDL should reject creation of widgets that duplicate main window for apps having active web view template

---

src/components/application_manager/include/application_manager/resumption/resumption_data_processor.h
src/components/application_manager/src/resumption/resumption_data_processor.cc

Covered by ATF test script
All data members inside of that class were not thread safe. Corresponding locks have been added to avoid possible data races and make that class more reliable.

Fix data races around ResumptionDataProcessor

---

src/components/application_manager/include/application_manager/display_capabilities_builder.h
src/components/application_manager/include/application_manager/resumption/resume_ctrl.h
src/components/application_manager/include/application_manager/resumption/resume_ctrl_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/on_bc_system_capability_updated_notification_from_hmi.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc
src/components/application_manager/src/display_capabilities_builder.cc
src/components/application_manager/src/resumption/resume_ctrl_impl.cc
src/components/application_manager/test/include/application_manager/mock_resume_ctrl.h

There was an issue with OnSCU notification on app registration observed for the main window. This notification can't be sent
to mobile app too early because state controller did not set initial default HMI level for it so policy manager just rejects
this notification on attempt to send it upon registration.
To avoid that issue, mandatory capabilities caching has been added for main window on app registration. SDL will additionaly
postpone capabilities for all other windows in case of resumption. SDL will stop waiting for capabilities notification once HMI level
of application was set. If SDL receives onSCU notification during app registration and it is the only window to wait then SDL will
send …

Fix OnSCU notification on app registration

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/on_bc_system_capability_updated_notification_from_hmi.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/on_bc_system_capability_updated_notification_from_hmi.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/get_system_capability_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_system_capability_updated_notification.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/on_bc_system_capability_updated_notification_from_hmi_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_system_capability_updated_notification_test.cc

Fixes [FORDTCN-7048](https://adc.luxoft.com/jira/browse/FORDTCN-7048)
This PR providing the next changes for the `OnSystemCapabilityupdated` notification:
- In the case when the notification from HMI contains an application id, it should be forwarded to the mobile application only if it has been subscribed on it, otherwise the notification should be ignored.
- In the case when the notification from HMI contains an application id, it should be ignored.

Processing OnSystemCapabilityUpdated with video stream capabilities

---

src/components/application_manager/include/application_manager/message_helper.h
src/components/application_manager/src/application_manager_impl.cc
src/components/application_manager/src/message_helper/message_helper.cc
src/components/application_manager/src/resumption/resumption_data_processor.cc

Covered by ATF test scripts
The issue was that resumption data processor did not subscribe to `VR.AddCommand` requests sent to HMI and as a result, ignored them and proceed with resumption.
Also fixed sending of `VR.DeleteCommand` for a choice sets in case of rollback.
Also fixed HMI level resumption for app in case another media app is in LIMITED.

Fix VR.AddCommand error response handling

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_system_capability_updated_notification.cc

Remove redundant app id checking in the OnSystemCapabilityUpdatedNotification. The same check exists in the BCOnSystemCapabilityUpdatedNotification.

Remove application id checking the OnSystemCapabilityUpdatedNotification

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_system_capability_updated_notification_test.cc

Fix failed Unit test which ckeck the case when an application id is absent in the incoming message. According to the current implementation, the OnBCSystemCapabilityUpdatedNotificationFromHMI has the same check, so in this notification it is redundant check.

Fix failed Unit tests for OnSystemCapabilityUpdatedNotification

---

src/components/application_manager/include/application_manager/message_helper.h
src/components/application_manager/include/application_manager/resumption/resume_ctrl.h
src/components/application_manager/include/application_manager/resumption/resume_ctrl_impl.h
src/components/application_manager/include/application_manager/resumption/resumption_data_processor.h
src/components/application_manager/include/application_manager/state_controller_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/ui_create_window_request.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/ui_create_window_request.cc
src/components/application_manager/src/application_data_impl.cc
src/components/application_manager/src/display_capabilities_builder.cc
src/components/application_manager/src/message_helper/message_helper.cc
src/components/application_manager/src/resumption/resume_ctrl_impl.cc
src/components/application_manager/src/resumption/resumption_data_processor.cc
src/components/application_manager/src/state_controller_impl.cc
src/components/application_manager/test/include/application_manager/mock_resume_ctrl.h
src/components/include/application_manager/state_controller.h

Covered by ATF test scripts
- Add logic of CreateWindow resumption into processor class
- Remove unused functions from resumption controller
- Add widget windows postponing logic to state controller
- Fix waiting for non-request messages in processor
- Fix capabilities reset for widgets

Widgets data resumption error handling

---

src/components/application_manager/src/state_controller_impl.cc

Fixes #7092(https://adc.luxoft.com/jira/browse/FORDTCN-7092)
Covered by ATF test scripts
There was noticed an issue with the conflict resolution when 1st app has been resumed to FULL and the 2nd app is being resumed to LIMITED. In that case state controller wrongly resolves HMI level of 1st application to LIMITED however it is still can be in FULL. The logic of conflict resolution has been updated to prevent this. Now, state controller will additionally verify HMI level of resumed application vs conflicting application, so if the 2nd app was resumed NOT to FULL then 1st app will keep its current HMI level as this is not considered to be a conflict.

Fix LIMITED-LIMITED HMI level conflict resolution

---

src/components/application_manager/include/application_manager/display_capabilities_builder.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_system_capability_updated_notification.cc
src/components/application_manager/src/display_capabilities_builder.cc

Fixes #[7166](https://adc.luxoft.com/jira/browse/FORDTCN-7166)
There was a gap in logic of processing resuming app, which has only main window, which is not cached. Before we had logic for processing not resumed app with only main window and resuming app, which may have one or more cached windows.

Fix problem with OnSCU notification during resumption with only main window

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/on_system_capability_updated_notification.cc

Fixes [#7258](https://adc.luxoft.com/jira/browse/FORDTCN-7258)
There might be a situation that `applications()` call returns a collection of app pointers including the apps which registration is currently in progress. These applications might have not initialized yet extensions so on attempt to extract some extension
by uid there will be a `DCHECK` error. To avoid that, more protective way to extract app extension was used. Additionally, `DISPLAYS` check has been moved before extension check as it much faster and also avoids redundant checks.

Fix extension extractions while traversing apps

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_app_extension.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/get_interior_vehicle_data_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_rpc_plugin.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/CMakeLists.txt
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/button_press_request_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/get_interior_vehicle_data_request_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/on_interior_vehicle_data_notification_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/rc_get_interior_vehicle_data_consent_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/set_interior_vehicle_data_request_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/rc_app_extension_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/resource_allocation_manager/resource_allocation_manager_impl_test.cc

Fixes [FORDTCN-7210](https://adc.luxoft.com/jira/browse/FORDTCN-7210)
This PR provides the next changes:
- Saving ModuleInfo into the resumption data;
- Updated hash after subscribe/unsubscribe on a VD;

Add saving ModuleInfo into the resumption data and updating app hash after subscribe/unsubscribe on a VD

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/hmi/on_bc_system_capability_updated_notification_from_hmi_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/add_command_request_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/create_interaction_choice_set_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/register_app_interface_request_test.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/reset_global_properties_test.cc

In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-6865
- Fix sdl_commands_test_unity
In accordance with the [[SDL-0190] Handle response from HMI during resumption data](https://github.com/LuxoftSDL/sdl_core/pull/84) implementation

[SDL-0190] Update commands unit tests

---

src/components/application_manager/rpc_plugins/app_service_rpc_plugin/test/app_service_plugin/app_service_app_extension_test.cc
src/components/application_manager/rpc_plugins/vehicle_info_plugin/test/commands/mobile/unsubscribe_vehicle_request_test.cc
src/components/application_manager/test/application_helper_test.cc
src/components/application_manager/test/resumption/resume_ctrl_test.cc

In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-6865
- Fix AppManager unit tests (resume_ctrl_test.cc and application_helper_test.cc )
- Fix AppService unit tests (app_service_app_extension_test.cc )
- Fix UnsubscribeVehicleDataRequest unit tests 
In accordance with the [[SDL-0190] Handle response from HMI during resumption data](https://github.com/LuxoftSDL/sdl_core/pull/84) implementation

[SDL-0190] Update unit tests

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/get_interior_vehicle_data_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/get_interior_vehicle_data_request_test.cc

In the scope of https://adc.luxoft.com/jira/browse/FORDTCN-7215
https://github.com/LuxoftSDL/sdl_atf_test_scripts/pull/61
SDL should respond with the WARNINGS result code if already subscribed app tries to subscribe to the same module

[SDL-0188] WARNINGS at the double subscription

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/sdl_pending_resumption_handler.cc
src/components/application_manager/src/event_engine/event_dispatcher_impl.cc

Fix https://adc.luxoft.com/jira/browse/FORDTCN-7299 
If a subscription is the last request for resumption, that resumption data processor will revert resumption after it `ClearPendingResumptionRequests` will be called before `SDLPendingResumptionHandler::on_event`, and resumption data processor will think that vehicle data was not subscribed successfully.
Quick fix is reordered subscription to response event. 
SO that pending resumption handler will be subscribed first and redumption data processor the second 
Also renamed ClearPendingResumption to OnResumptionRevert, that is more correct 
Second fix : 
event dispatcher was not support recursive on_event because of shared state. Make variable observers_ local,so it could ro recursive on_event call

[SDL-0190] Fix issue with processing of on_events

---

src/components/application_manager/src/application_manager_impl.cc
src/components/application_manager/src/resumption/resumption_data_processor.cc

Fixes [FORDTCN-7298](https://adc.luxoft.com/jira/browse/FORDTCN-7298)
There was found two issues:
1. Commands revert has been done by internal id instead of cmdID which makes resumption data revert sensitive to commands order. This peace of code was updated to work properly with cmdID despite of commands resumption order
2. There was a missing part of logic regarding reset of VRHelp property. Because this property was not considered during revert, in some cases SDL does not trigger sending of SetGP. Missing check has been added to resolve that issue

[SDL-0190] Fix wrong revert of GP and Commands

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_pending_resumption_handler.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_rpc_plugin.cc

In scope of https://adc.luxoft.com/jira/browse/FORDTCN-7367
Save interior vehicle data to cache during resumption after receiving a successful response from HMI. 
Add interior_data_cache_ as a class member to the rc_pending_resumption_handler

[SDL-0188] Save interior vehicle data to cache during resumption

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc

OnHashUpdate will be sent once after resumption is finished (from here https://github.com/LuxoftSDL/sdl_core/blob/feature/sdl_0188_interior_vehicle_data_resumption/src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/register_app_interface_request.cc#L788)
So I just removed redundant OnHashUpdate sending during RevertResumption

[SDL-0188] Remove redundant OnHashUpdate sending

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/rc_pending_resumption_handler.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_app_extension.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_pending_resumption_handler.cc

During resumption, RC app subscribes to VD before sending GETIVD(subscribe=true) on HMI.
If HMI respond with error to this subscription, SDL should erase internal subscription to appropriate module typle.

Unsubscribe app from interior vehicle data if subscription was not success during resumption

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/rc_helpers.cc
src/components/application_manager/src/resumption/resumption_data_processor.cc

Provides checking the 'is_subscribed' parameter in a HMI response

Add checking is subscribe parameter to clarify if response is successful

---

src/components/interfaces/HMI_API.xml

Fixes [FORDTCN-7949](https://adc.luxoft.com/jira/browse/FORDTCN-7949)
This PR makes **minor** API changes.
TBD
There is a need in adding support for numeric keyboard. To solve this problem new struct "KeyboardCapabilities" is added to HMI API to inform apps about keyboard capabilities of HMI. Also "NUMERIC" value is added to "KeyboardLayout" enum. This enum value should allow apps to use numeric keypad.

Adding support for numeric keyboard

---

src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/commands/mobile/button_press_request.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/commands/mobile/set_interior_vehicle_data_request.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/resource_allocation_manager.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/resource_allocation_manager_impl.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_get_interior_vehicle_data_consent_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/button_press_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/set_interior_vehicle_data_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/rc_command_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/resource_allocation_manager_impl.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/button_press_request_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/rc_get_interior_vehicle_data_consent_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/commands/set_interior_vehicle_data_request_test.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/test/include/rc_rpc_plugin/mock/mock_resource_allocation_manager.h

Fixes [FORDTCN-2939](https://adc.luxoft.com/jira/browse/FORDTCN-2939) and [FORDTCN-12134](https://adc.luxoft.com/jira/browse/FORDTCN-12134)
ATF test scripts, affected UTs are updated
* SDL shall respond to a SetInteriorVehicleData request within 10 seconds after a request is received if SDL allows or denies the request without asking for the driver’s permission. If the driver’s permission pop up is needed, SDL shall respond to the request within 20 seconds.
* SDL shall respond to a ButtonPress request within 10 seconds after a request is received if SDL allows or denies the request without asking for the driver’s permission. If the driver’s permission pop up is needed, SDL shall respond to the request within 20 seconds.
* …

[SDL-0189] Fix timeout for requests with consent

---

src/components/application_manager/include/application_manager/request_info.h
src/components/application_manager/src/request_info.cc
src/components/application_manager/src/request_timeout_handler_impl.cc
src/components/application_manager/test/request_timeout_handler_test.cc

Fixes #[FORDTCN-2944]
In case we changed the ResetTimeout for more than 10 seconds, we were unable to change it to a different value.
To fix this problem, we can update the ResetTimeout to the request with the corresponding hmi_correlation_id in RequestTimeoutHandlerImpl::on_event() method.

[SDL-0189]  Fix onResetTimeout twice notification

---

src/components/application_manager/src/commands/command_request_impl.cc

Fixes [FORDTCN-12133](https://adc.luxoft.com/jira/browse/FORDTCN-12133)
ATF test script
There is a requirement for SDL for `Alert` RPC to not apply timeout if request contains soft buttons. The same requirement should work for `SubtleAlert` RPC. So corresponding changes were added to CommandRequestImpl class to prevent adding such request to request map inside of RequestTimeoutHandler class.

[SDL-0189] Restrict timeout for subtle alert with soft buttons

---

src/components/application_manager/include/application_manager/request_controller_impl.h
src/components/application_manager/src/application_manager_impl.cc
src/components/application_manager/src/request_controller_impl.cc
src/components/include/application_manager/request_controller.h
src/components/include/test/application_manager/mock_request_controller.h

Fixes #[FORDTCN-12131]
This PR is **[ready ]** for review.
During ATF testing, it was noticed that the SDL crashes after the tests are completed.
This happened due to the incorrect termination of the requests_controller.

[SDL-0189] fix crash sdl_core on close

---

src/components/application_manager/src/request_controller_impl.cc

Fixes #[FORDTCN-12163]
ATF, manual
This PR provide change logic for handling HMI requests with soft buttons.
If request to HMI contains some soft buttons request_controller should wait until user make interaction
and do not apply onTimeout() method for this request.

Fix OnResetTimeout for Alerts with soft buttons

---

src/components/application_manager/include/application_manager/request_controller_impl.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/commands/mobile/button_press_request.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/include/rc_rpc_plugin/commands/mobile/set_interior_vehicle_data_request.h
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/hmi/rc_get_interior_vehicle_data_consent_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/button_press_request.cc
src/components/application_manager/rpc_plugins/rc_rpc_plugin/src/commands/mobile/set_interior_vehicle_data_request.cc
src/components/application_manager/src/request_controller_impl.cc
src/components/application_manager/src/request_timeout_handler_impl.cc
src/components/application_manager/test/request_timeout_handler_test.cc
src/components/include/application_manager/request_controller.h
src/components/include/test/application_manager/mock_request_controller.h

Remove default timeout adjustments from core:
RC plugin:
- ButtonPress request
- SetIVD request
- RC.GetIVD consent

Remove default timeout adjustments from core

---

src/components/application_manager/include/application_manager/application.h
src/components/application_manager/include/application_manager/application_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/unsubscribe_button_request.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/unsubscribe_button_response.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/mobile/unsubscribe_button_request.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/unsubscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/unsubscribe_button_response.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/unsubscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/hmi_command_factory.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/unsubscribe_button_request_test.cc
src/components/application_manager/src/application_impl.cc
src/components/application_manager/test/include/application_manager/mock_application.h

Fixes #[FORDTCN-12188]
This PR makes **[no ]** API changes.
ATF test scripts, affected UTs are updated
Add HMI unsubscribe button request and response

unsubscribe buttons impl

---

src/components/application_manager/include/application_manager/commands/command_impl.h
src/components/application_manager/include/application_manager/commands/command_request_impl.h
src/components/application_manager/include/application_manager/commands/request_from_hmi.h
src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/commands/hmi/as_get_app_service_data_request_from_hmi.cc
src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/commands/hmi/as_perform_app_service_interaction_request_from_hmi.cc
src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/commands/mobile/get_app_service_data_request.cc
src/components/application_manager/rpc_plugins/app_service_rpc_plugin/src/commands/mobile/perform_app_service_interaction_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/unsubscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/create_window_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_interaction_choice_set_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/delete_window_request.cc
src/components/application_manager/src/commands/command_impl.cc
src/components/application_manager/src/commands/command_request_impl.cc
src/components/application_manager/src/commands/request_from_hmi.cc
src/components/application_manager/src/commands/request_to_hmi.cc
src/components/application_manager/src/resumption/resumption_data_processor_impl.cc

Fixes [FORDTCN-12270](https://adc.luxoft.com/jira/browse/FORDTCN-12270)
Unify approach to result codes processing
For now we have 6 successful result codes:
SUCCESS,
WARNINGS,
WRONG_LANGUAGE,
RETRY,
SAVED,
TRUNCATED_DATA
Also I didn't change existing logic for UNSUPPORTED_RESOURCE code processing, so only refactoring is there.

[SDL 0192] Unify approach to result codes processing

---

src/components/application_manager/include/application_manager/application.h
src/components/application_manager/include/application_manager/application_impl.h
src/components/application_manager/include/application_manager/application_manager_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_response.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/unsubscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/unsubscribe_button_response.cc
src/components/application_manager/src/application_impl.cc
src/components/application_manager/src/application_manager_impl.cc
src/components/application_manager/test/include/application_manager/mock_application.h
src/components/include/application_manager/application_manager.h
src/components/include/test/application_manager/mock_application_manager.h

Fixes [FORDTCN-12264](https://adc.luxoft.com/jira/browse/FORDTCN-12264)
Add new methods to ApplicationManager class to handle expired button requests. Also delete redundant methods from Application class and all dead code from hmi::SubscribeButtonRequest/hmi::UnsubscribeButtonRequest classes.

[SDL 0192] Revert expired button requests if response was received after timeout

---

src/components/application_manager/rpc_plugins/sdl_rpc_plugin/test/commands/mobile/on_button_notification_commands_test.cc
src/components/application_manager/src/application_impl.cc
src/components/application_manager/src/commands/button_notification_to_mobile.cc
src/components/application_manager/test/application_impl_test.cc

Was removed subscription to the custom button by default.
Also, added check if the app is actually subscribed to CUSTOM_BUTTON like for all other buttons.

Fix CUSTOM_BUTTON subscription logic

---

src/components/application_manager/include/application_manager/resumption/resumption_data_processor_impl.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/include/sdl_rpc_plugin/commands/hmi/subscribe_button_request.h
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/hmi/subscribe_button_request.cc
src/components/application_manager/rpc_plugins/sdl_rpc_plugin/src/commands/mobile/subscribe_button_request.cc
src/components/application_manager/src/resumption/resumption_data_processor_impl.cc
src/components/application_manager/test/resumption/resume_ctrl_test.cc

Fixes [FORDTCN-12277](https://adc.luxoft.com/jira/browse/FORDTCN-12277)
This PR makes **no ** API changes.
Separate subscription processing logic for mobile requests and resumption:
* Delete on_event() method and parent event_observer from hmi::SubscribeButtonRequest class
* Move logic with application subscription to on_event() method of mobile::SubscribeButtonRequest class during mobile request processing
* Move logic with application subscription to ResumptionDataProcessor during Resumption to avoid race conditions with already deleted on_event() method from hmi::SubscribeButtonRequest class

Separate subscription processing logic for mobile requests and resumption
